# -*- coding: utf-8 -*-
"""AUC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hgGcn6wb2zsiKz3LgwVVGa5O6nqOl5n5
"""

import numpy as np
import pandas as pd

"""Using random basic datase from open sklearn set"""

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

"""Random Forest Classifier"""

from sklearn.ensemble import RandomForestClassifier

random_forest_model = RandomForestClassifier(n_estimators=100, random_state=42)
random_forest_model.fit(X_train, y_train)

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(random_state=42)
logistic_model.fit(X_train, y_train)

y_pred_rf = random_forest_model.predict_proba(X_test)[:, 1]

y_pred_lr = logistic_model.predict_proba(X_test)[:, 1]

dataframe_for_test = pd.DataFrame({'CurrentTrue': y_test, 'Forest': y_pred_rf, 'Logistic': y_pred_lr})

import matplotlib.pyplot as plt

from sklearn.metrics import roc_curve, auc

plt.figure(figsize=(10,8))

forestpr, testpr, _ = roc_curve(dataframe_for_test['CurrentTrue'], dataframe_for_test['Forest'])
forest_roc_auc = auc(forestpr, testpr)
plt.plot(forestpr, testpr, label=f'{'Forest'} (AUC = {forest_roc_auc:.2f})')

logisticpr, testlpr, _ = roc_curve(dataframe_for_test['CurrentTrue'], dataframe_for_test['Forest'])
logistic_roc_auc = auc(logisticpr, testlpr)
plt.plot(logisticpr, testlpr, label=f'{'Logistic'} (AUC = {logistic_roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'r--', label='Random Guess')

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC')
plt.legend()
plt.show()