# -*- coding: utf-8 -*-
"""Iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jiBJeu23h3FFQc1iW6UsQ_qz0-__0hOW
"""

import pandas as pd
import numpy as np

from sklearn import datasets

def load_iris_dataframe():

    iris = datasets.load_iris()

    X = pd.DataFrame(iris.data, columns=iris.feature_names)

    X.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

    y = pd.Series(iris.target, name='species')

    return X, y

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import cross_val_score

def objective_factory(X, y, model_name, cv, n_jobs=1):

    def objective(trial):

        n_features = trial.suggest_int("n_features", 1, X.shape[1])


        rfe_estimator_C = trial.suggest_float("rfe_C", 1e-3, 1e3, log=True)
        rfe_est = LogisticRegression(

            penalty='l2',
            C=rfe_estimator_C,
            solver='lbfgs',
            multi_class='multinomial',
            max_iter=500,
            random_state=42
        )

        rfe = RFE(estimator=rfe_est, n_features_to_select=n_features, step=1)

        if model_name == 'logreg':
            C = trial.suggest_float("logreg_C", 1e-3, 1e3, log=True)
            clf = LogisticRegression(
                penalty='l2',
                C=C,
                solver='lbfgs',
                multi_class='multinomial',
                max_iter=1000,
                random_state=42
            )
        elif model_name == 'knn':
            n_neighbors = trial.suggest_int("n_neighbors", 1, 30)
            weights = trial.suggest_categorical("weights", ["uniform", "distance"])
            p = trial.suggest_categorical("p", [1, 2])
            clf = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights, p=p, n_jobs=n_jobs)
        else:
            raise ValueError("Unknown model_name")

        pipe = Pipeline([
            ('scaler', StandardScaler()),
            ('rfe', rfe),
            ('clf', clf)
        ])


        scores = cross_val_score(pipe, X, y, cv=cv, scoring='accuracy', n_jobs=n_jobs)

        return float(np.mean(scores))

    return objective

import optuna

def run_optuna_search(X, y, model_name, cv, n_trials=50, n_jobs=1):

    study = optuna.create_study(direction='maximize', sampler=optuna.samplers.TPESampler(seed=42))

    obj = objective_factory(X, y, model_name, cv, n_jobs=n_jobs)

    study.optimize(obj, n_trials=n_trials, n_jobs=1)  # optuna parallelism: set n_jobs cautiously
    return study

def build_best_pipeline_from_study(study, model_name):
    params = study.best_params.copy()


    n_features = params.pop("n_features")

    rfe_C = params.pop("rfe_C")

    rfe_est = LogisticRegression(penalty='l2', C=rfe_C, solver='lbfgs',
                                 multi_class='multinomial', max_iter=500, random_state=42)
    rfe = RFE(estimator=rfe_est, n_features_to_select=n_features, step=1)


    if model_name == 'logreg':

        C = params.pop("logreg_C")

        clf = LogisticRegression(penalty='l2', C=C, solver='lbfgs',
                                 multi_class='multinomial', max_iter=1000, random_state=42)

    elif model_name == 'knn':

        n_neighbors = params.pop("n_neighbors")

        weights = params.pop("weights")

        p = params.pop("p")

        clf = KNeighborsClassifier(n_neighbors=n_neighbors, weights=weights, p=p, n_jobs=1)

    else:

        raise ValueError("Unknown model_name")

    pipe = Pipeline([
        ('scaler', StandardScaler()),
        ('rfe', rfe),
        ('clf', clf)
    ])

    return pipe

from sklearn.model_selection import StratifiedKFold, cross_val_predict

X, y = load_iris_dataframe()
print(X.head())

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import warnings
warnings.filterwarnings("ignore")

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

print("\nStart Optuna dla Logistic Regression...")
study_logreg = run_optuna_search(X, y, model_name='logreg', cv=cv, n_trials=40, n_jobs=1)
print("Best logreg trial:", study_logreg.best_value)
print(study_logreg.best_params)

print("\nStart Optuna dla k-NN...")
study_knn = run_optuna_search(X, y, model_name='knn', cv=cv, n_trials=40, n_jobs=1)
print("Best knn trial:", study_knn.best_value)
print(study_knn.best_params)

from scipy.stats import wilcoxon

pipe_logreg = build_best_pipeline_from_study(study_logreg, 'logreg')
pipe_knn = build_best_pipeline_from_study(study_knn, 'knn')

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
accs_logreg = []
accs_knn = []
y_true_all = []
y_pred_logreg_all = []
y_pred_knn_all = []
fold_idx = 0
for train_idx, test_idx in skf.split(X, y):

  fold_idx += 1
  X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
  y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]


  pipe_logreg.fit(X_train, y_train)
  y_pred_log = pipe_logreg.predict(X_test)
  acc_log = accuracy_score(y_test, y_pred_log)
  accs_logreg.append(acc_log)

  pipe_knn.fit(X_train, y_train)
  y_pred_k = pipe_knn.predict(X_test)
  acc_k = accuracy_score(y_test, y_pred_k)
  accs_knn.append(acc_k)

  y_true_all.extend(y_test.tolist())
  y_pred_logreg_all.extend(y_pred_log.tolist())
  y_pred_knn_all.extend(y_pred_k.tolist())

  print(f"Fold {fold_idx}: logreg acc = {acc_log:.4f}, knn acc = {acc_k:.4f}")

accs_logreg = np.array(accs_logreg)
accs_knn = np.array(accs_knn)

print("\nAccuracies per fold (LogReg):", accs_logreg)
print("Mean ± std (LogReg): {:.4f} ± {:.4f}".format(accs_logreg.mean(), accs_logreg.std()))
print("\nAccuracies per fold (kNN):", accs_knn)
print("Mean ± std (kNN): {:.4f} ± {:.4f}".format(accs_knn.mean(), accs_knn.std()))


stat, pvalue = wilcoxon(accs_logreg, accs_knn, zero_method='wilcox', alternative='two-sided')
print("\nWilcoxon signed-rank test between LogReg and kNN (paired fold accuracies):")
print(f"statistic = {stat:.4f}, p-value = {pvalue:.6f}")
if pvalue < 0.05:
     print("Wniosek: różnica statystycznie istotna przy poziomie 0.05")
else:
     print("Wniosek: brak istotnej różnicy przy poziomie 0.05")


print("\n--- Szczegółowy raport dla LogReg (agregowane predykcje z CV) ---")
print(classification_report(y_true_all, y_pred_logreg_all, target_names=datasets.load_iris().target_names, digits=4))
print("Confusion matrix (LogReg):")
print(confusion_matrix(y_true_all, y_pred_logreg_all))

print("\n--- Szczegółowy raport dla kNN (agregowane predykcje z CV) ---")
print(classification_report(y_true_all, y_pred_knn_all, target_names=datasets.load_iris().target_names, digits=4))
print("Confusion matrix (kNN):")
print(confusion_matrix(y_true_all, y_pred_knn_all))


print("\nBest parameters found (Logistic Regression study):")
print(study_logreg.best_params)
print("\nBest parameters found (k-NN study):")
print(study_knn.best_params)