# -*- coding: utf-8 -*-
"""TestNaiveBayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpBRbz-Y2MGQcN4_Xlyqv2VvjtqriiXQ
"""

import pandas as pd

df = pd.read_csv('t_1_classification_bayes.csv')
df.columns = ['feature0','color','feature2','class']

"""Klasyfikujemy (1,blue,2)

Priory
"""

p_class_up = ((df['class'] == 'UP').sum())/(df['class'].count())
p_class_down = ((df['class'] == 'DOWN').sum())/(df['class'].count())

"""Estymaty warunkowe"""

p_feature_0_class_up = (((df['class'] == 'UP') & (df['feature0'] == 1)).sum())/((df['class'] == 'UP').sum())
p_color_class_up = (((df['class'] == 'UP') & (df['color'] == 'blue')).sum())/((df['class'] == 'UP').sum())
p_feature_2_class_up = (((df['class'] == 'UP') & (df['feature2'] == 2)).sum())/((df['class'] == 'UP').sum())

p_1_blue_2_class_up = p_class_up * p_feature_0_class_up * p_color_class_up * p_feature_2_class_up

p_feature_0_class_down = (((df['class'] == 'DOWN') & (df['feature0'] == 1)).sum())/((df['class'] == 'DOWN').sum())
p_color_class_down = (((df['class'] == 'DOWN') & (df['color'] == 'blue')).sum())/((df['class'] == 'DOWN').sum())
p_feature_2_class_down = (((df['class'] == 'DOWN') & (df['feature2'] == 2)).sum())/((df['class'] == 'DOWN').sum())

p_1_blue_2_class_down = p_class_down * p_feature_0_class_down * p_color_class_down * p_feature_2_class_down

denominator_of_bayes = p_1_blue_2_class_up + p_1_blue_2_class_down
bayes_of_class_up = p_1_blue_2_class_up/denominator_of_bayes
bayes_of_class_down = p_1_blue_2_class_down/denominator_of_bayes

print(bayes_of_class_up)
print(bayes_of_class_down)

if(bayes_of_class_up > bayes_of_class_down):
  print("UP")
else:
  print("DOWN")