# -*- coding: utf-8 -*-
"""PimaIndiansDiabetes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13M0PqspxI92AxFl485cuX7QTE29pR57S

This Notebook presents a **Classification Analysis** of Pima Indians Diabetes dataset .

The dataset was obtained from [kaggle.com](https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database?select=diabetes.csv). Access (19.12.2025):

*This dataset is originally from the National Institute of Diabetes and Digestive and Kidney Diseases. The objective of the dataset is to diagnostically predict whether or not a patient has diabetes, based on certain diagnostic measurements included in the dataset. Several constraints were placed on the selection of these instances from a larger database. In particular, all patients here are females at least 21 years old of Pima Indian heritage.*
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import kagglehub

# Download latest version
path = kagglehub.dataset_download("uciml/pima-indians-diabetes-database")

print("Path to dataset files:", path)

df = pd.read_csv("/kaggle/input/pima-indians-diabetes-database/diabetes.csv")

"""**1. Data Exploration**


"""

df.head()
df.info()
df.describe()

print("Shape of dataset:", df.shape)
print(df["Outcome"].value_counts())
print("\nPClass proportion:")
print(df["Outcome"].value_counts(normalize=True))

"""a) Feature Description:

The dataset consists of numerical features describing medical measurements of patients, as well as a binary target variable *Outcome*, indicationg the presence (1) or absence (0) of diabetes.

*   Pregnancies - Number of times pregnant
*   Glucose - Plasma glucose concentration a 2 hours in an oral glucose tolerance test

*   BloodPressure	- Diastolic blood pressure (mm Hg)


*   SkinThickness - Triceps skin fold thickness (mm)


*   Insulin  -  2-Hour serum insulin (mu U/ml)


*   BMI  -  Body mass index (weight in kg/(height in m)^2)


*   DiabetesPedigreeFunction  -  Diabetes pedigree function


*   Age  -  Age (years)
*   Outcome  -   Class variable (0 or 1) 268 of 768 are 1, the others are 0

b) Identification and Removal of Invalid Measurements

In several features, zero values are **physically impossible** due to the nature of the measured quantities and therefore indicate *missing or incorrectly recorded measurements*, rather than valid observations. Such values must be identified and handled prior to further analysis.
"""

invalid_zero_cols = [
    "Glucose",
    "BloodPressure",
    "SkinThickness",
    "BMI"
]

for col in invalid_zero_cols:
  n_zeros = (df[col] == 0).sum()
  print(f"{col}:zeros = {n_zeros}")

df[invalid_zero_cols].hist(bins=20, figsize=(12, 8))
plt.tight_layout()
plt.show()

df_clean = df.copy()

df_clean[invalid_zero_cols] = df_clean[invalid_zero_cols].replace(0, np.nan)

print(df_clean.isna().sum())

df_clean = df_clean.dropna()

print(df_clean.shape)

print(df_clean["Outcome"].value_counts())

selected_features = [
    "Glucose",
    "BMI",
    "Age",
    "Insulin",
    "BloodPressure",
    "Outcome"
]

sns.pairplot(
    df_clean[selected_features],
    hue="Outcome",
    diag_kind="kde",
    corner=True
)

plt.suptitle("Pairplot – Pima Indians Diabetes (without incorrect values)", y=1.02)
plt.show()

"""Based on the pairplot, a noticeable class separation with respect to the target variable *Outcome* can be observed, particularly for the *Glucose* and *BMI* features."""

plt.figure(figsize=(10, 8))
sns.heatmap(
    df_clean.corr(),
    annot=True,
    fmt=".2f",
    cmap="coolwarm",
    square=True
)
plt.show()

"""**2. Preparing Data**"""

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

X = df_clean.drop(columns="Outcome")
y = df_clean["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

print("Train set shape:", X_train.shape)
print("Test set shape:", X_test.shape)

print("\nClass distribution in train set:")
print(y_train.value_counts(normalize=True))

print("\nClass distribution in test set:")
print(y_test.value_counts(normalize=True))

"""Features selection will be included with Optuna, atm it's only Pipeline's definition"""

logreg_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("classifier", LogisticRegression(
            max_iter=1000,
            random_state=42
        ))
    ]
)

knn_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("classifier", KNeighborsClassifier())
    ]
)

"""**3. Hiperparameters**"""

import optuna

from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.metrics import roc_auc_score

cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

def objective_logreg(trial):

  C = trial.suggest_float("C", 1e-3, 1e-2, log=True)
  penalty = trial.suggest_categorical("penalty", ["l1", "l2"])

  logreg_pipeline = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("classifier", LogisticRegression(
                C=C,
                penalty=penalty,
                solver="liblinear",
                max_iter=1000,
                random_state=42
            ))
        ]
    )

  scores = cross_val_score(
      logreg_pipeline,
      X_train,
      y_train,
      cv=cv,
      scoring="roc_auc"
  )

  return scores.mean()

study_logreg = optuna.create_study(direction="maximize")
study_logreg.optimize(objective_logreg, n_trials=50)

print("ROC-AUC:", study_logreg.best_value)
print("Params: ", study_logreg.best_params)

def objective_knn(trial):

    n_neighbors = trial.suggest_int("n_neighbors", 3, 30)
    weights = trial.suggest_categorical("weights", ["uniform", "distance"])
    metric = trial.suggest_categorical("metric", ["euclidean", "manhattan"])

    knn_pipeline = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("classifier", KNeighborsClassifier(
                n_neighbors=n_neighbors,
                weights=weights,
                metric=metric
            ))
        ]
    )

    scores = cross_val_score(
        knn_pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring="roc_auc"
    )

    return scores.mean()

study_knn = optuna.create_study(direction="maximize")
study_knn.optimize(objective_knn, n_trials=50)

print("ROC-AUC:", study_knn.best_value)
print("params:", study_knn.best_params)

from sklearn.feature_selection import RFE
from sklearn.feature_selection import SequentialFeatureSelector

"""Removing features based on model weights"""

def objective_logreg_rfe(trial):

  c = trial.suggest_float("C", 1e-3, 1e2, log=True)
  penalty = trial.suggest_categorical("penalty", ["l1", "l2"])
  nFeatures = trial.suggest_int("n_features", 3, X_train.shape[1])

  base_estimator = LogisticRegression(
      C=c,
      penalty=penalty,
      solver="liblinear",
      max_iter=1000,
      random_state=42
  )

  pipeline = Pipeline(
      steps=[
          ("scaler", StandardScaler()),
          ("rfe", RFE(
              estimator=base_estimator,
              n_features_to_select=nFeatures
          )),
          ("classifier", base_estimator)
      ]
  )

  scores = cross_val_score(
      pipeline,
      X_train,
      y_train,
      cv=cv,
      scoring="roc_auc"
  )

  return scores.mean()

study_logreg_rfe = optuna.create_study(direction="maximize")
study_logreg_rfe.optimize(objective_logreg_rfe, n_trials=50)

print("Best ROC-AUC:", study_logreg_rfe.best_value)
print("Best parameters:", study_logreg_rfe.best_params)

"""There's no reason of using RFE for kNN, better way is SequentialFeatureSelector"""

def objective_knn_sfs(trial):

    n_neighbors = trial.suggest_int("n_neighbors", 3, 30)
    weights = trial.suggest_categorical("weights", ["uniform", "distance"])
    metric = trial.suggest_categorical("metric", ["euclidean", "manhattan"])
    n_features = trial.suggest_int("n_features", 3, X_train.shape[1] - 1)

    knn = KNeighborsClassifier(
        n_neighbors=n_neighbors,
        weights=weights,
        metric=metric
    )

    pipeline = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("sfs", SequentialFeatureSelector(
                estimator=knn,
                n_features_to_select=n_features,
                direction="forward",
                scoring="roc_auc",
                cv=cv,
                n_jobs=-1
            )),
            ("classifier", knn)
        ]
    )

    scores = cross_val_score(
        pipeline,
        X_train,
        y_train,
        cv=cv,
        scoring="roc_auc"
    )

    return scores.mean()

study_knn_sfs = optuna.create_study(direction="maximize")
study_knn_sfs.optimize(objective_knn_sfs, n_trials=50)

"""Cross validation"""

from sklearn.model_selection import cross_val_score

best_logreg_params = study_logreg_rfe.best_params

best_C = best_logreg_params["C"]
best_penalty = best_logreg_params["penalty"]
best_n_features_logreg = best_logreg_params["n_features"]

"""**Final Logistic Regression Model**"""

final_logreg_estimator = LogisticRegression(
    C=best_C,
    penalty=best_penalty,
    solver="liblinear",
    max_iter=1000,
    random_state=42
)

final_logreg_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("rfe", RFE(
            estimator=final_logreg_estimator,
            n_features_to_select=best_n_features_logreg
        )),
        ("classifier", final_logreg_estimator)
    ]
)

logreg_cv_scores = cross_val_score(
    final_logreg_pipeline,
    X_train,
    y_train,
    cv=cv,
    scoring="roc_auc"
)

print("Logistic Regression + RFE")
print("ROC-AUC scores per fold:", logreg_cv_scores)
print("Mean ROC-AUC:", logreg_cv_scores.mean())
print("Std ROC-AUC:", logreg_cv_scores.std())

"""**Final Model kNN**"""

best_knn_params = study_knn_sfs.best_params

best_n_neighbors = best_knn_params["n_neighbors"]
best_weights = best_knn_params["weights"]
best_metric = best_knn_params["metric"]
best_n_features_knn = best_knn_params["n_features"]

final_knn_estimator = KNeighborsClassifier(
    n_neighbors=best_n_neighbors,
    weights=best_weights,
    metric=best_metric
)

final_knn_pipeline = Pipeline(
    steps=[
        ("scaler", StandardScaler()),
        ("sfs", SequentialFeatureSelector(
            estimator=final_knn_estimator,
            n_features_to_select=best_n_features_knn,
            direction="forward",
            scoring="roc_auc",
            cv=cv,
            n_jobs=-1
        )),
        ("classifier", final_knn_estimator)
    ]
)

knn_cv_scores = cross_val_score(
    final_knn_pipeline,
    X_train,
    y_train,
    cv=cv,
    scoring="roc_auc"
)

print("kNN + Wrapper (SFS)")
print("ROC-AUC scores per fold:", knn_cv_scores)
print("Mean ROC-AUC:", knn_cv_scores.mean())
print("Std ROC-AUC:", knn_cv_scores.std())

"""**Wilcoxon's Test**"""

from scipy.stats import wilcoxon

assert len(logreg_cv_scores) == len(knn_cv_scores)

differences = logreg_cv_scores - knn_cv_scores
print(differences)

stat, p_value = wilcoxon(
    logreg_cv_scores,
    knn_cv_scores,
    alternative="two-sided"
)


print(f"Wilcoxon statistic: {stat}")
print(f"p-value: {p_value:.5f}")

stat_greater, p_greater = wilcoxon(
    logreg_cv_scores,
    knn_cv_scores,
    alternative="greater"
)

print(f"p-value (LogReg > kNN): {p_greater:.5f}")

stat_less, p_less = wilcoxon(
    logreg_cv_scores,
    knn_cv_scores,
    alternative="less"
)

print(f"p-value (kNN > LogReg): {p_less:.5f}")