# -*- coding: utf-8 -*-
"""BasicSummaryWriter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yoSwrqFdrB_76UwJbP__HnXOi8-pODa8
"""

import math
import torch
import torch.nn as nn
from torch.utils.tensorboard import SummaryWriter

device = 'cuda' if torch.cuda.is_available() else 'cpu'

writer = SummaryWriter('runs/test1')

model = nn.Sequential(
    nn.Linear(1, 5),
    nn.Linear(5, 5),
    nn.Linear(5,1)
).to(device)

sample_x = torch.tensor([1.0]).unsqueeze(0)

writer.add_graph(model, sample_x.to(device))

for trial in range(1000):
  loss = math.exp(-trial/30)

  writer.add_scalars(
      main_tag='optuna',
      tag_scalar_dict={'loss': loss},
      global_step=trial
  )

writer.flush()

writer = SummaryWriter('/runs/test2')

model = nn.Sequential(nn.Linear(1, 1)).to(device)

writer.add_graph(model, sample_x.to(device))

for epoch in range(100):
  loss = math.exp(-epoch/30)
  val_loss = 2 * math.exp(-epoch/15)

  writer.add_scalars(
      main_tag='loss',
      tag_scalar_dict={
          'training': loss,
          'validation': val_loss
      },
      global_step=epoch
  )

writer.flush()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs