# -*- coding: utf-8 -*-
"""DifferentNNShape.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OLMankH7fkPQROk8p_XHQt9zEpNnnWrU
"""

import numpy as np

"""1. Wczytanie rzeczywistego zbioru regresyjnego z OpenML (np. mały/średni zbiór tablicowy z jedną zmienną
ciągłą jako target).
"""

from sklearn.datasets import fetch_openml

data = fetch_openml(name="boston", version=1, as_frame=True)

X = data.data.values.astype(np.float32)
y = data.target.values.astype(np.float32)

"""2.
Podział danych na zbiory: treningowy, walidacyjny i testowy (np. 60/20/20 z użyciem train_test_split). W zadaniu będzie trzeba porównać różną liczbę warstw i neuronów i ocenić je najpierw na podstawie zbioru walidacyjnego a dopiero na końcu na podstawie zbioru testowego. Test powinien być całkowicie niezależny a więc wykonuje się go na końcu. Jeżeli wcześniej oceniano by model z użyciem zbioru testowego a nie walidacyjnego wystąpiłby data leakage.
"""

from sklearn.model_selection import train_test_split, KFold

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.4,
    random_state=42
)

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.5,
    random_state=42
)

"""Optymalizacja do Cross-Validation

Tak aby zbiór testowy pozostał nietknięty. (tylko train i val)
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

import torch

X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

X_val = torch.tensor(X_val, dtype=torch.float32)
y_val = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

dimensionOfInput = X_train.shape[1] #liczna cech wejściowych

import torch.nn as nn

class FlexibleMLP(nn.Module):


    def __init__(self, dimensionOfInput, otherLayers):

        super(FlexibleMLP, self).__init__()

        self.layers = nn.ModuleList()

        prev_dim = dimensionOfInput

        for h in otherLayers:

            self.layers.append(nn.Linear(prev_dim, h))

            prev_dim = h

        self.outputLayer = nn.Linear(prev_dim, 1)

        self.relu = nn.ReLU()

    def forward(self, x):
        for layer in self.layers:

            x = self.relu(layer(x))

        x = self.outputLayer(x)

        return x

def quantityOfParameters(model):
    return sum(p.numel() for p in model.parameters() if p.requires_grad)

architectures = {
    "deep_narrow": [64, 64, 64, 64, 64, 64],
    "shallow_wide": [220, 220],
    "pyramid": [64, 128, 256, 128, 64]
}

import torch.optim as optim

import matplotlib.pyplot as plt

def train_model(model, X_train, y_train, X_val, y_val,
                epochs=100, lr=0.001):

    criterion = nn.MSELoss()


    optimizer = optim.Adam(model.parameters(), lr=lr) #pierwsza aktualizacja wag całej sieci

    train_losses = []
    val_losses = []

    best_val_loss = float("inf") #nieskończoność jako abstrakcyjne maksimum
    best_state = None

    for epoch in range(epochs):


        model.train()

        optimizer.zero_grad()

        pred_train = model(X_train)

        train_loss = criterion(pred_train, y_train)

        train_loss.backward() #liczenie gradientów

        optimizer.step() #aktualizacja wag


        model.eval()

        with torch.no_grad():

            pred_val = model(X_val)

            val_loss = criterion(pred_val, y_val)


        train_losses.append(train_loss.item())


        val_losses.append(val_loss.item())

        if val_loss.item() < best_val_loss:

            best_val_loss = val_loss.item()

            best_state = model.state_dict()

    model.load_state_dict(best_state)

    return train_losses, val_losses, best_val_loss

results = {}

for name, hidden_layers in architectures.items():

    print(f"\n===== {name} =====")

    model = FlexibleMLP(dimensionOfInput, hidden_layers)

    param_count = quantityOfParameters(model)
    print("Warstwy:", hidden_layers)
    print("Liczba parametrów:", param_count)

    train_losses, val_losses, best_val = train_model(
        model,
        X_train,
        y_train,
        X_val,
        y_val
    )

    # Test MSE
    model.eval()
    with torch.no_grad():
        test_pred = model(X_test)
        test_mse = nn.MSELoss()(test_pred, y_test).item()

    results[name] = {
        "model": model,
        "params": param_count,
        "train_losses": train_losses,
        "val_losses": val_losses,
        "best_val_mse": best_val,
        "test_mse": test_mse
    }

plt.figure(figsize=(10, 6))

for name in results:
    plt.plot(results[name]["val_losses"], label=f"{name} val")

plt.xlabel("Epoka")
plt.ylabel("MSE Loss")
plt.legend()
plt.title("Porównanie strat walidacyjnych")
plt.show()