# -*- coding: utf-8 -*-
"""HyperparametersCharts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOFWfVQM2_dBC--n8XkpL1J4qQBDUxjB
"""

import torch
import torch.nn as nn
import torch.optim as optim

import numpy as np

X = np.linspace(-5, 5, 1000)
y = X**2 + 6.7*np.random.randn(1000)

X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.25)

X_train = torch.FloatTensor(X_train)
y_train = torch.FloatTensor(y_train)

X_val = torch.FloatTensor(X_val)
y_val = torch.FloatTensor(y_val)

[X_val, y_val]

import optuna

from torch.utils.tensorboard import SummaryWriter

best_val_loss = float("inf")

def objective(trial):

  global best_val_loss  # Declare best_val_loss as global

  learningRate = trial.suggest_float("lr", 1e-5, 1e-1, log=True)
  hiddenSize = trial.suggest_int("hidden_size", 4, 32)
  countOfLayers = trial.suggest_int("num_layers", 1, 3)

  layers = []
  inputSize = 1

  for _ in range(countOfLayers):
    layers.append(nn.Linear(inputSize, hiddenSize))
    layers.append(nn.ReLU())
    inputSize = hiddenSize

  layers.append(nn.Linear(inputSize, 1))
  model = nn.Sequential(*layers)

  criterion = nn.MSELoss()
  optimizer = optim.Adam(model.parameters(), lr=learningRate)

  writer = SummaryWriter(f"runs/optuna/trial_{trial.number}")

  epochs = 45

  for epoch in range(epochs):

    model.train()

    optimizer.zero_grad()

    pred = model(X_train)

    loss = criterion(pred, y_train)

    loss.backward()
    optimizer.step()

    model.eval()
    with torch.no_grad():
      val_pred = model(X_val)
      val_loss = criterion(val_pred, y_val)

    writer.add_scalars(
        "Loss",
        {
            "train": loss.item(),
            "validation": val_loss.item(),
        },
        epoch
    )

    if val_loss.item() < best_val_loss:
        best_val_loss = val_loss.item()
        torch.save(model.state_dict(), f"best_model_trial_{trial.number}.pth")

  hparams = {
      "lr": learningRate,
      "hidden_size": hiddenSize,
      "num_layers": countOfLayers
  }

  metrics = {
      "hparam/loss": val_loss.item()
  }

  writer.add_hparams(hparams, metrics)
  writer.flush()
  writer.close()

  return val_loss.item()

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=12)

best_trial = study.best_trial.number
print("Best trial:", best_trial)

print("Best trial:")
print(study.best_trial.params)
print("Best loss:", study.best_trial.value)

df = study.trials_dataframe()
df.to_csv("optuna_results.csv", index=False)

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir runs