# -*- coding: utf-8 -*-
"""LossChart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18ztpeEGI_vgQBogeIRvXAl4Yru2N0gnJ
"""

import torch
import torch.nn as nn
import torch.optim as optim

import numpy as np

from sklearn.model_selection import train_test_split

X = np.linspace(-2, 2, 200)
y = X**2 + 0.2*np.random.randn(200)

X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2)

X_train = torch.FloatTensor(X_train)
y_train = torch.FloatTensor(y_train)

X_val = torch.FloatTensor(X_val)
y_val = torch.FloatTensor(y_val)

model = nn.Sequential(
    nn.Linear(1, 16),
    nn.ReLU(),
    nn.Linear(16, 1)
)

criterion = nn.MSELoss()
optimizer = optim.Adam(model.parameters(), lr=0.01)

from torch.utils.tensorboard import SummaryWriter

writer = SummaryWriter("runs/training_example")

epochs = 100

for epoch in range(epochs):

  model.train()
  optimizer.zero_grad()

  y_pred = model(X_train)
  train_loss = criterion(y_pred, y_train)

  train_loss.backward()
  optimizer.step()

  model.eval()
  with torch.no_grad():
    val_pred = model(X_val)
    val_loss = criterion(val_pred, y_val)

  writer.add_scalars(
      "Loss",
      {
          "train": train_loss.item(),
          "validation": val_loss.item(),
      },
      epoch
  )

  if epoch % 10 == 0:
    print(f"Epoch {epoch}: train={train_loss.item():.4f}, val={val_loss.item():.4f}")

writer.flush()

# Commented out IPython magic to ensure Python compatibility.
from torch.utils import tensorboard
# %load_ext tensorboard
# %tensorboard --logdir runs