# -*- coding: utf-8 -*-
"""RegresjaGlebokoscSzerokosc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaCpZYwvLmDt5LqpI-tQfelvMrnuyT-8
"""

import numpy as np

"""1. Wczytanie rzeczywistego zbioru regresyjnego z OpenML (np. mały/średni zbiór tablicowy z jedną zmienną
ciągłą jako target).
"""

from sklearn.datasets import fetch_openml

data = fetch_openml(name="boston", version=1, as_frame=True)

X = data.data.values
y = data.target.values.astype(np.float32)

"""2.
Podział danych na zbiory: treningowy, walidacyjny i testowy (np. 60/20/20 z użyciem train_test_split). W zadaniu będzie trzeba porównać różną liczbę warstw i neuronów i ocenić je najpierw na podstawie zbioru walidacyjnego a dopiero na końcu na podstawie zbioru testowego. Test powinien być całkowicie niezależny a więc wykonuje się go na końcu. Jeżeli wcześniej oceniano by model z użyciem zbioru testowego a nie walidacyjnego wystąpiłby data leakage.
"""

from sklearn.model_selection import train_test_split

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

"""Skalowanie dany, tak aby ich średnia ~ 0 a odchylanie = 1.

x` = (x - mu)/sigma
"""

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

import torch

X_train = torch.tensor(X_train, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)

X_val = torch.tensor(X_val, dtype=torch.float32)
y_val = torch.tensor(y_val, dtype=torch.float32).view(-1, 1)

X_test = torch.tensor(X_test, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

input_dim = X_train.shape[1] #liczna cech wejściowych

"""Model regresyjny MLP w PyTorch w postaci klasy dziedziczącej po nn.Module, wykorzystującej
nn.ModuleList do przechowywania warstw ukrytych
"""

import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, input_dim, hidden_dim, n_hidden):
        super(MLP, self).__init__()

        self.hidden_layers = nn.ModuleList()

        # pierwsza warstwa
        self.hidden_layers.append(nn.Linear(input_dim, hidden_dim))

        # kolejne warstwy ukryte
        for _ in range(n_hidden - 1):
            self.hidden_layers.append(nn.Linear(hidden_dim, hidden_dim))

        # warstwa wyjściowa
        self.output_layer = nn.Linear(hidden_dim, 1)

        self.relu = nn.ReLU()

    def forward(self, x):
        for layer in self.hidden_layers:
            x = self.relu(layer(x))
        x = self.output_layer(x)
        return x

"""Dodanie nieliniowości ReLU

Trening kilku wariantów architektury, przy tym samym setupie treningu (MSELoss, optimizer Adam, stały
learning rate, stała liczba epok, ten sam batch size):

MSE = (1/n)*Suma z (y_true = y_pred)^2
"""

import torch.optim as optim

def train_model(model, X_train, y_train, X_val, y_val, epochs=100, lr=0.001):
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float('inf')
    best_model_state = None

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        outputs = model(X_train)
        loss = criterion(outputs, y_train)
        loss.backward() #backpropagation liczenie gradientów
        optimizer.step() # aktualizacja wag

        # walidacja
        model.eval()
        with torch.no_grad():
            val_outputs = model(X_val)
            val_loss = criterion(val_outputs, y_val)

        if val_loss.item() < best_val_loss:
            best_val_loss = val_loss.item()
            best_model_state = model.state_dict()

    model.load_state_dict(best_model_state)

    return best_val_loss

"""Zmienna głębokość przy stałej szerokości: n_hidden {1, 2, 4} przy hidden_dim np. 64"""

results = []

for n_hidden in [1, 2, 4]:
    model = MLP(input_dim, hidden_dim=64, n_hidden=n_hidden)
    val_loss = train_model(model, X_train, y_train, X_val, y_val)

    with torch.no_grad():
        test_loss = nn.MSELoss()(model(X_test), y_test).item()

    results.append(("depth", n_hidden, 64, val_loss, test_loss))

"""Zmienna szerokość przy stałej głębokości: hidden_dim {16, 64, 256} przy n_hidden np. 2"""

for hidden_dim in [16, 64, 256]:
    model = MLP(input_dim, hidden_dim=hidden_dim, n_hidden=2)
    val_loss = train_model(model, X_train, y_train, X_val, y_val)

    with torch.no_grad():
        test_loss = nn.MSELoss()(model(X_test), y_test).item()

    results.append(("width", 2, hidden_dim, val_loss, test_loss))

"""Porównanie"""

print("Typ | Warstwy | Neurony | Val MSE | Test MSE")
print("-" * 50)
for r in results:
    print(f"{r[0]} | {r[1]} | {r[2]} | {r[3]:.4f} | {r[4]:.4f}")