# -*- coding: utf-8 -*-
"""RegresjaZOptuna.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRercdYSSe5wFj3ukXgKUWWyFDViEWY7
"""

import numpy as np

"""1. Wczytanie rzeczywistego zbioru regresyjnego z OpenML (np. mały/średni zbiór tablicowy z jedną zmienną
ciągłą jako target).
"""

from sklearn.datasets import fetch_openml

data = fetch_openml(name="boston", version=1, as_frame=True)

X = data.data.values.astype(np.float32)
y = data.target.values.astype(np.float32)

"""2.
Podział danych na zbiory: treningowy, walidacyjny i testowy (np. 60/20/20 z użyciem train_test_split). W zadaniu będzie trzeba porównać różną liczbę warstw i neuronów i ocenić je najpierw na podstawie zbioru walidacyjnego a dopiero na końcu na podstawie zbioru testowego. Test powinien być całkowicie niezależny a więc wykonuje się go na końcu. Jeżeli wcześniej oceniano by model z użyciem zbioru testowego a nie walidacyjnego wystąpiłby data leakage.
"""

from sklearn.model_selection import train_test_split, KFold

X_train_all, X_temp, y_train_all,   y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

"""Optymalizacja do Cross-Validation

Tak aby zbiór testowy pozostał nietknięty. (tylko train i val)
"""

X_opt = np.vstack([X_train_all, X_val])
y_opt = np.concatenate([y_train_all, y_val])

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_opt = scaler.fit_transform(X_opt)
X_test = scaler.transform(X_test)

import torch

X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

dimensionOfInput = X_train.shape[1] #liczna cech wejściowych

"""Model regresyjny MLP w PyTorch w postaci klasy dziedziczącej po nn.Module, wykorzystującej
nn.ModuleList do przechowywania warstw ukrytych
"""

import torch.nn as nn

class MLP(nn.Module):
    def __init__(self, dimensionOfInput, hidden_dim, n_hidden):
        super(MLP, self).__init__()

        self.hidden_layers = nn.ModuleList()


        self.hidden_layers.append(nn.Linear(dimensionOfInput, hidden_dim))


        for _ in range(n_hidden - 1):
            self.hidden_layers.append(nn.Linear(hidden_dim, hidden_dim))

        # warstwa wyjściowa
        self.output_layer = nn.Linear(hidden_dim, 1)

        self.relu = nn.ReLU()

    def forward(self, x):
        for layer in self.hidden_layers:
            x = self.relu(layer(x))
        x = self.output_layer(x)
        return x

"""Dodanie nieliniowości ReLU

Trening kilku wariantów architektury, przy tym samym setupie treningu (MSELoss, optimizer Adam, stały
learning rate, stała liczba epok, ten sam batch size):

MSE = (1/n)*Suma z (y_true = y_pred)^2
"""

import torch.optim as optim

def train_model(model, X_train, y_train, X_val, y_val, epochs=100, lr=0.001):
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float('inf')
    best_model_state = None

    for epoch in range(epochs):
        model.train()
        optimizer.zero_grad()

        outputs = model(X_train)
        loss = criterion(outputs, y_train)
        loss.backward() #backpropagation liczenie gradientów
        optimizer.step() # aktualizacja wag

        # walidacja
        model.eval()
        with torch.no_grad():
            val_outputs = model(X_val)
            val_loss = criterion(val_outputs, y_val)

        if val_loss.item() < best_val_loss:
            best_val_loss = val_loss.item()
            best_model_state = model.state_dict()

    model.load_state_dict(best_model_state)

    return best_val_loss

import optuna

def train_single_model(model, X_train, y_train, X_val, y_val,
                       epochs=100, lr=0.001):
    criterion = nn.MSELoss()
    optimizer = optim.Adam(model.parameters(), lr=lr)

    best_val_loss = float("inf")
    best_state = None

    for epoch in range(epochs):
        model.train()

        optimizer.zero_grad()
        pred = model(X_train)
        loss = criterion(pred, y_train)
        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            val_pred = model(X_val)
            val_loss = criterion(val_pred, y_val)

        if val_loss.item() < best_val_loss:
            best_val_loss = val_loss.item()
            best_state = model.state_dict()

    model.load_state_dict(best_state)
    return best_val_loss

def objective(trial):
    hidden_dim = trial.suggest_categorical("hidden_dim", [16, 32, 64, 128, 256])
    n_hidden = trial.suggest_int("n_hidden", 1, 5)

    kf = KFold(n_splits=5, shuffle=True, random_state=42)
    val_losses = []

    for train_idx, val_idx in kf.split(X_opt):
        X_train_fold = X_opt[train_idx]
        X_val_fold = X_opt[val_idx]
        y_train_fold = y_opt[train_idx]
        y_val_fold = y_opt[val_idx]

        X_train_tensor = torch.tensor(X_train_fold, dtype=torch.float32)
        y_train_tensor = torch.tensor(y_train_fold, dtype=torch.float32).view(-1, 1)

        X_val_tensor = torch.tensor(X_val_fold, dtype=torch.float32)
        y_val_tensor = torch.tensor(y_val_fold, dtype=torch.float32).view(-1, 1)

        model = MLP(dimensionOfInput, hidden_dim, n_hidden)

        fold_loss = train_single_model(
            model,
            X_train_tensor,
            y_train_tensor,
            X_val_tensor,
            y_val_tensor
        )

        val_losses.append(fold_loss)

    return np.mean(val_losses)

study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=20)

print("\nNajlepsze parametry:")
print(study.best_params)

best_hidden_dim = study.best_params["hidden_dim"]
best_n_hidden = study.best_params["n_hidden"]

kf = KFold(n_splits=5, shuffle=True, random_state=42)
ensemble_models = []

for fold, (train_idx, val_idx) in enumerate(kf.split(X_opt)):
    X_train_fold = X_opt[train_idx]
    X_val_fold = X_opt[val_idx]
    y_train_fold = y_opt[train_idx]
    y_val_fold = y_opt[val_idx]

    X_train_tensor = torch.tensor(X_train_fold, dtype=torch.float32)
    y_train_tensor = torch.tensor(y_train_fold, dtype=torch.float32).view(-1, 1)

    X_val_tensor = torch.tensor(X_val_fold, dtype=torch.float32)
    y_val_tensor = torch.tensor(y_val_fold, dtype=torch.float32).view(-1, 1)

    model = MLP(dimensionOfInput, best_hidden_dim, best_n_hidden)

    train_single_model(
        model,
        X_train_tensor,
        y_train_tensor,
        X_val_tensor,
        y_val_tensor
    )

    ensemble_models.append(model)

print("\nWytrenowano 5 modeli ensemble.")

with torch.no_grad():
    predictions = []

    for model in ensemble_models:
        model.eval()
        pred = model(X_test_tensor)
        predictions.append(pred.numpy())

    ensemble_pred = np.mean(predictions, axis=0)

ensemble_pred_tensor = torch.tensor(ensemble_pred, dtype=torch.float32)
test_mse = nn.MSELoss()(ensemble_pred_tensor, y_test_tensor)

print(f"\nEnsemble Test MSE: {test_mse.item():.4f}")